### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rtfpessoa** [yujinakayama/atom-auto-update-packages#12]
I'm constantly getting this error, any idea what can be causing it?
Atom debug log bellow. BTW besides de call stack exceeded the Atom message to create this issue exceeded the size too and I had to do this manually :(

[Full StackTrace](http://paste.ubuntu.com/9587486/)

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.2
**Thrown From**: [auto-update-packages](https://github.com/yujinakayama/atom-auto-update-packages) package, v0.2.2
### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:53

RangeError: Maximum call stack size exceeded
  at Object.module.exports.updatePackagesIfAutoUpdateBlockIsExpired (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:53:8)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:33:6)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:134:21)
  at Object.module.exports.enableAutoUpdate (/Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:39:39)
  at /Users/rtfpessoa/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe 
....................................................

```
### Commands

```
```
### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "csslint",
      "terminal",
      "terminal",
      "terminal",
      "terminal"
    ],
    "useReactEditor": true
  }
}
```
### Installed Packages

``` coffee
# User
auto-update-packages, v0.2.2
autocomplete-bibtex, v0.4.1
clang-format, v1.5.0
color-picker, v1.2.6
css-color-highlighting, v0.2.4
git-tab-status, v1.3.0
javascript-snippets, v1.0.0
language-csharp, v0.3.0
language-latex, v0.4.1
language-lisp, v0.1.1
language-nginx, v0.4.0
language-scala, v1.1.0
monokai, v0.9.0
pdf-view, v0.13.0
php-checkstyle, v0.15.0
pretty-json, v0.3.1
script, v2.15.1
status-bar, v0.54.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by Jwagner347** [comment]
I'm still getting this error
