### ISSUE TITLE
Uncaught Error: Cannot find module 'glob'

### ISSUE THREAD

**Issue by Belelros** [yujinakayama/atom-auto-update-packages#13]
Opening Atom with it enabled gives me this

**Atom Version**: 0.168.0
**System**: Mac OS X 10.10.1
**Thrown From**: [auto-update-packages](https://github.com/yujinakayama/atom-auto-update-packages) package, v0.2.2

### Stack Trace

Uncaught Error: Cannot find module 'glob'

```
At module.js:346

Error: Cannot find module 'glob'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Users/alaguna/.atom/packages/auto-update-packages/lib/package-updater.coffee:2:8)
  at Object.<anonymous> (/Users/alaguna/.atom/packages/auto-update-packages/lib/package-updater.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:61:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.module.exports.updatePackages (/Users/alaguna/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:56:23)
  at Object.module.exports.updatePackagesIfAutoUpdateBlockIsExpired (/Users/alaguna/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:53:8)
  at Object.module.exports.enableAutoUpdate (/Users/alaguna/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:33:6)
  at /Users/alaguna/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:25:8

```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, v0.2.2
autoclose-html, v0.13.0
autocomplete-plus, v1.0.0
compare-files, v0.2.6
linter, v0.9.0
linter-jshint, v0.1.0
seti-syntax, v0.2.1
seti-ui, v0.5.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by LarsVonQualen** [comment]
This problems seems to still exist for some of us? I'm just opening a fresh Atom. The funny thing is that everything works as it should.

Could this be triggered by wrong permissions on some of the files in the npm cache, or something similarly obscure?

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [auto-update-packages](https://github.com/yujinakayama/atom-auto-update-packages) package, v0.2.2


### Stack Trace

Uncaught Error: Cannot find module 'glob'

```
At module.js:330

Error: Cannot find module 'glob'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/larsvonqualen/.atom/packages/auto-update-packages/lib/package-updater.coffee:6:10)
    at Object.<anonymous> (/Users/larsvonqualen/.atom/packages/auto-update-packages/lib/package-updater.coffee:139:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
     -0:04.8.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "color-picker"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
auto-update-packages, v0.2.2
autoclose-html, v0.16.2
command-logger, v0.23.0
docblockr, v0.7.2
editor-stats, v0.17.0
language-jade, v0.4.0
visual-bell, v1.0.0

# Dev
No dev packages
```

**Comment by ShinraEngineer** [comment]
This error is still occurring in the latest version of ATOM. 

Here are the steps to reproduce:

1. Open Git CMD. 
2. Run the following command: 

git clone https://github.com/yujinakayama/atom-auto-update-packages.git

3. Open ATOM. 
4. Error appears. 

**Atom**: 1.21.0-beta1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [auto-update-packages](https://github.com/yujinakayama/atom-auto-update-packages) package 1.0.1


### Stack Trace

Uncaught Error: Cannot find module 'glob'

```
At C:\Users\Steven\AppData\Local\atom\app-1.21.0-beta1\resources\app\static\<embedded>:1

Error: Cannot find module 'glob'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.21.0-beta1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-auto-update-packages/lib/package-updater.coffee:2:8)
    at /packages/atom-auto-update-packages/lib/package-updater.coffee:1:1)
    at /packages/atom-auto-update-packages/lib/package-updater.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/native-compile-cache.js:66:33)
    at Object.updatePackages (/packages/atom-auto-update-packages/lib/auto-update-packages.coffee:58:23)
    at Object.updatePackagesIfAutoUpdateBlockIsExpired (/packages/atom-auto-update-packages/lib/auto-update-packages.coffee:55:8)
    at Object.enableAutoUpdate (/packages/atom-auto-update-packages/lib/auto-update-packages.coffee:35:6)
    at /packages/atom-auto-update-packages/lib/auto-update-packages.coffee:26:8
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.12 
auto-update-packages 1.0.1 
atom-beautify 0.30.5 
atom-clock 0.1.15 
expose 0.14.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
open-recent 5.0.0 
pigments 0.40.2 
todo-show 2.0.0 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-paths 2.11.0 
busy-signal 1.4.3 
console-panel 0.2.1 
emmet 2.4.3 
git-blame 1.2.2 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.5 
language-liquid 0.6.0 
language-nsis 6.3.0 
linter 2.2.0 
linter-eslint 8.3.2 
linter-rubocop 2.1.1 
linter-scss-lint 3.1.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
project-manager 3.3.5 
```

**Comment by ahmedmoeen1234** [comment]
how to install package
