### ISSUE TITLE
Failed to activate the auto-update-packages package

### ISSUE THREAD

**Issue by vraravam** [yujinakayama/atom-auto-update-packages#23]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [auto-update-packages](https://github.com/yujinakayama/atom-auto-update-packages) package, v0.2.2

### Stack Trace

Failed to activate the auto-update-packages package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/vijay/.atom/packages/auto-update-packages/lib/auto-update-packages.coffee:21:23)
  at Package.module.exports.Package.activateNow (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
  at /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
  at Package.module.exports.Package.measure (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.activate (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
  at /usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
  at Config.module.exports.Config.transact (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
  at Atom.module.exports.Atom.startEditorWindow (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/atom.js:623:21)
  at Object.<anonymous> (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///usr/local/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/static/index.js:54:25)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": true,
    "disabledPackages": [
      "language-c",
      "archive-view",
      "welcome",
      "jshint",
      "language-clojure",
      "language-coffee-script",
      "language-gfm",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-toml",
      "package-generator",
      "save-session"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "coverage",
      "tmp/",
      "log/"
    ],
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  },
  "auto-update-packages": {
    "intervalMinutes": 30
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, v0.2.2
autocomplete-plus-async, v0.22.0
change-case, v0.5.1
clipboard-history, v0.6.4
coffee-compile, v0.13.0
coffeescript-preview, v1.0.0
file-icons, v1.5.4
git-blame, v0.4.0
git-tab-status, v1.7.0
highlight-line, v0.10.2
highlight-selected, v0.9.2
language-rspec, v0.3.0
linter, v0.12.1
linter-csslint, v0.0.11
linter-golint, v0.2.0
linter-jshint, v0.1.2
linter-less, v0.3.1
linter-rubocop, v0.2.2
linter-scss-lint, v0.0.14
minimap, v4.7.6
minimap-git-diff, v4.1.2
rails-rspec, v0.3.1
recent-files, v0.3.0
ruby-block-converter, v3.3.0
ruby-syntax-replacer, v0.3.2
search-all-keybindings, v0.1.1
symbols-tree-view, v0.9.2
syntax-settings, v0.7.1
tab-history, v0.4.0
tree-ignore, v0.2.5

# Dev
No dev packages
```

**Comment by yujinakayama** [comment]
Fixed in auto-update-packages 1.0.0. (#31)
