### ISSUE TITLE
Error at installing | Windows

### ISSUE THREAD

**Issue by EspGameplayer** [yujinakayama/atom-auto-update-packages#50]
I had an error at installing this plugin on Atom 1.44.0 and I don't understand the log. Does this plugin even support Windows?

```
Installing “auto-update-packages@1.0.1” failed.Hide output…

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for auto-update-packages@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JoseAntonio\.atom\.apm\_logs\2020-03-08T19_36_05_016Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\JoseAntonio\\AppData\\Local\\atom\\app-1.44.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\JoseAntonio\\AppData\\Local\\atom\\app-1.44.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\JoseAntonio\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\JoseAntonio\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/auto-update-packages/versions/1.0.1/tarball',
1 verbose cli   '--target=4.2.7',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v10.2.1
4 verbose npm-session 448fecb199a8d856
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://www.atom.io/api/packages/auto-update-packages/versions/1.0.1/tarball 1334ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/auto-update-packages/versions/1.0.1/tarball fetched in 1373ms
9 timing stage:loadCurrentTree Completed in 1737ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 timing stage:rollbackFailedOptional Completed in 1ms
17 timing stage:runTopLevelLifecycles Completed in 1742ms
18 silly saveTree apm-install-dir-12028-24772-17q21we.t9in
19 verbose stack Error: Unsupported platform for auto-update-packages@1.0.1: wanted {"name":"auto-update-packages","version":"1.0.1","engines":{"atom":">=0.206.0"},"os":["darwin"],"dependencies":{"glob":"^3.2.9","fs-plus":"^2.0.4"},"optionalDependencies":{},"devDependencies":{"coffee-script":"^1.7.1","coffeelint":"^1.1.0"},"bundleDependencies":false,"peerDependencies":{},"deprecated":false,"_resolved":"https://www.atom.io/api/packages/auto-update-packages/versions/1.0.1/tarball","_integrity":"sha512-GSr77hjwtR03lJyZLm/KlH/fXBhPpSXKXLC54n6rPq7K82qM409q9WWWj/7pwq4QRYnSG/e7a6Ynqm4nyN8nzA==","_shasum":"07e66b823f125479dabc2de49626fa620be28a30","_shrinkwrap":null,"bin":null,"_id":"auto-update-packages@1.0.1","_from":"https://www.atom.io/api/packages/auto-update-packages/versions/1.0.1/tarball","_requested":{"type":"remote","raw":"https://www.atom.io/api/packages/auto-update-packages/versions/1.0.1/tarball","rawSpec":"https://www.atom.io/api/packages/auto-update-packages/versions/1.0.1/tarball","saveSpec":"https://www.atom.io/api/packages/auto-update-packages/versions/1.0.1/tarball","fetchSpec":"https://www.atom.io/api/packages/auto-update-packages/versions/1.0.1/tarball"},"_spec":"https://www.atom.io/api/packages/auto-update-packages/versions/1.0.1/tarball","_where":"C:\\Users\\JOSEAN~1\\AppData\\Local\\Temp\\apm-install-dir-12028-24772-17q21we.t9in"} (current: {"os":"win32","cpu":"x64"})
19 verbose stack     at checkPlatform (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\npm-install-checks\index.js:45:14)
19 verbose stack     at thenWarnEngineIssues (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\lib\install\validate-args.js:52:5)
19 verbose stack     at a (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\iferr\iferr.js:3:64)
19 verbose stack     at checkEngine (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\npm-install-checks\index.js:24:10)
19 verbose stack     at module.exports.isInstallable (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\lib\install\validate-args.js:49:3)
19 verbose stack     at Array.<anonymous> (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
19 verbose stack     at LOOP (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
19 verbose stack     at C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
19 verbose stack     at checkSelf (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\lib\install\validate-args.js:57:72)
19 verbose stack     at Array.<anonymous> (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
19 verbose stack     at LOOP (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
19 verbose stack     at C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
19 verbose stack     at hasMinimumFields (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\lib\install\validate-args.js:30:12)
19 verbose stack     at Array.<anonymous> (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
19 verbose stack     at LOOP (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
19 verbose stack     at chain (C:\Users\JoseAntonio\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
20 verbose pkgid auto-update-packages@1.0.1
21 verbose cwd C:\Users\JOSEAN~1\AppData\Local\Temp\apm-install-dir-12028-24772-17q21we.t9in
22 verbose Windows_NT 10.0.18362
23 verbose argv "C:\\Users\\JoseAntonio\\AppData\\Local\\atom\\app-1.44.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\JoseAntonio\\AppData\\Local\\atom\\app-1.44.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\JoseAntonio\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\JoseAntonio\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/auto-update-packages/versions/1.0.1/tarball" "--target=4.2.7" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
24 verbose node v10.2.1
25 verbose npm  v6.2.0
26 error code EBADPLATFORM
27 error notsup Unsupported platform for auto-update-packages@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
28 error notsup Valid OS:    darwin
28 error notsup Valid Arch:  any
28 error notsup Actual OS:   win32
28 error notsup Actual Arch: x64
29 verbose exit [ 1, true ]
```

**Comment by DerZyklop** [comment]
This ticket is a duplicate of #45
